import type { ExtractResult } from '../types/Appraisal';

const today = () => new Date().toISOString().slice(0, 10);

export const DEMO_EXTRACTS: Record<string, ExtractResult> = {
  'uad-sfr-greenwich': {
    header: {
      reviewerName: '',
      reviewDate: today(),
      borrowerName: 'Redacted UHNW Client',
      sellerName: 'Redacted UHNW Client',
      propertyAddress: '14 Hemlock Lane',
      city: 'Greenwich',
      state: 'CT',
      zip: '06830',
      opinionOfMarketValue: 4_850_000,
      effectiveDate: '2026-06-15',
      assignmentReason: 'Refinance',
      contractPrice: null,
      listingStatus: 'Not Listed',
      propertyValuationMethod: 'Traditional Appraisal',
      constructionMethod: 'Site Built',
      attachmentType: 'Detached',
      pud: false,
      condominium: false,
      cooperative: false,
      condop: false,
      subjectSiteOwnedInCommon: false,
      propertyOnNativeAmericanLands: false,
      unitsExcludingADUs: 1,
      accessoryDwellingUnits: 0,
      propertyRightsAppraised: 'Fee Simple',
      overallQuality: 'Q1',
      overallCondition: 'C3',
      marketValueCondition: 'As Is',
      appraiserName: 'James Whitfield, MAI',
      amcVendor: 'ProTeck Valuation Services',
      formType: 'UAD 3.6 URAR',
      legacyFormEquivalent: '1004 (Detached SFR)',
    },
    factualFlags: [
      {
        id: 'f1',
        category: 'bed_bath',
        title: 'Bath count mismatch across report sections',
        detail:
          'Room Summary lists 3 full + 1 half (3.1). Sketch labels 2 full + 1 half. Photos appear to document only 2 full baths.',
        sources: 'Room Summary vs Sketch vs Photos',
      },
      {
        id: 'f2',
        category: 'consistency',
        title: 'GLA mismatch — Room Summary vs Sketch',
        detail: 'Room Summary states 6,240 sq ft finished area; sketch area breakdown sums to 6,180 sq ft.',
        sources: 'Room Summary vs Sketch',
      },
      {
        id: 'f3',
        category: 'consistency',
        title: 'FEMA flood zone discrepancy',
        detail: 'Site section reports Zone X; flood certification on file indicates Zone AE.',
        sources: 'Appraisal Site section vs Flood Cert',
      },
      {
        id: 'f4',
        category: 'photos',
        title: 'Missing required subject photo',
        detail: 'Rear elevation photo not included in Subject Property exhibits.',
        sources: 'UAD 3.6 Photo Requirements — Subject Property',
      },
    ],
    photosCheck: [
      { id: 'p1', label: 'Subject Property photo', status: 'pass' },
      { id: 'p2', label: 'Property Access (Street Scene)', status: 'pass' },
      { id: 'p3', label: 'Rear elevation', status: 'fail', note: 'Missing' },
      { id: 'p4', label: 'Comp photos complete', status: 'pass' },
      { id: 'p5', label: 'Appraiser certification / signature', status: 'pass' },
    ],
  },

  'uad-2unit-hi': {
    header: {
      reviewerName: '',
      reviewDate: today(),
      borrowerName: 'Betty Borrower',
      sellerName: 'Sydney Seller',
      propertyAddress: '12345 Holiday Hwy',
      city: 'Surfside',
      state: 'HI',
      zip: '12345',
      opinionOfMarketValue: 195_000,
      effectiveDate: '2019-10-05',
      assignmentReason: 'Purchase',
      contractPrice: 160_000,
      listingStatus: 'Pending',
      propertyValuationMethod: 'Traditional Appraisal',
      constructionMethod: 'Site Built',
      attachmentType: 'Detached',
      pud: false,
      condominium: false,
      cooperative: false,
      condop: false,
      subjectSiteOwnedInCommon: false,
      propertyOnNativeAmericanLands: false,
      unitsExcludingADUs: 2,
      accessoryDwellingUnits: 0,
      propertyRightsAppraised: 'Fee Simple',
      overallQuality: 'Q5',
      overallCondition: 'C4',
      marketValueCondition: 'As Is',
      appraiserName: 'Tom Appraiser',
      amcVendor: 'Arthur Appraiser Appraisals',
      formType: 'UAD 3.6 URAR',
      legacyFormEquivalent: '1025 (2-4 Unit)',
    },
    factualFlags: [
      {
        id: 'f1',
        category: 'signature',
        title: 'Trainee appraiser — supervisory inspection scope',
        detail:
          'Appraiser is Trainee level. Supervisory Appraiser did not inspect exterior or interior — verify acceptable per engagement letter.',
        sources: 'Assignment / Certification section',
      },
      {
        id: 'f2',
        category: 'consistency',
        title: 'Unit room counts consistent',
        detail: 'Both units show 2 bed / 1 full bath in Room Summary and sketch — no mismatch flagged.',
        sources: 'Room Summary vs Sketch (informational)',
      },
    ],
    photosCheck: [
      { id: 'p1', label: 'Subject Property photo', status: 'pass' },
      { id: 'p2', label: 'Property Access (Street Scene)', status: 'pass' },
      { id: 'p3', label: 'Unit interior photos (each unit)', status: 'pass' },
      { id: 'p4', label: 'Appraiser certification / signature', status: 'pass' },
    ],
  },

  'uad-condo-ca': {
    header: {
      reviewerName: '',
      reviewDate: today(),
      borrowerName: 'Jane Condo-Buyer',
      sellerName: 'Grammy Gold Seller LLC',
      propertyAddress: 'Unit 1206, 500 Grammy Gold Blvd',
      city: 'Grammy Gold',
      state: 'CA',
      zip: '90021',
      opinionOfMarketValue: 778_000,
      effectiveDate: '2023-08-15',
      assignmentReason: 'Purchase',
      contractPrice: 775_000,
      listingStatus: 'Settled',
      propertyValuationMethod: 'Traditional Appraisal',
      constructionMethod: 'Site Built',
      attachmentType: 'Attached',
      pud: false,
      condominium: true,
      cooperative: false,
      condop: false,
      subjectSiteOwnedInCommon: true,
      propertyOnNativeAmericanLands: false,
      unitsExcludingADUs: 1,
      accessoryDwellingUnits: 0,
      propertyRightsAppraised: 'Fee Simple',
      overallQuality: 'Q3',
      overallCondition: 'C3',
      marketValueCondition: 'As Is',
      appraiserName: 'Lisa Nguyen, MAI',
      amcVendor: 'Clear Capital AMC',
      formType: 'UAD 3.6 URAR',
      legacyFormEquivalent: '1073 (Condominium)',
    },
    factualFlags: [
      {
        id: 'f1',
        category: 'photos',
        title: 'Comparable 2 front photo missing',
        detail: 'Sales Comparison Approach — Comp #2 has no front elevation photo in exhibits.',
        sources: 'Comparable exhibits',
      },
      {
        id: 'f2',
        category: 'detector',
        title: 'Smoke/CO detectors not addressed',
        detail: 'Unit Interior section does not mention smoke or CO detector presence.',
        sources: 'Unit Interior section',
      },
      {
        id: 'f3',
        category: 'bed_bath',
        title: 'Bed/bath counts consistent',
        detail: 'Room Summary (2 bed, 2.1 bath) matches sketch labels — no mismatch.',
        sources: 'Room Summary vs Sketch (informational)',
      },
    ],
    photosCheck: [
      { id: 'p1', label: 'Subject Property photo', status: 'pass' },
      { id: 'p2', label: 'Unit interior photos', status: 'pass' },
      { id: 'p3', label: 'Comp 2 front photo', status: 'fail', note: 'Missing' },
      { id: 'p4', label: 'Appraiser certification / signature', status: 'pass' },
    ],
  },
};

export function getDemoExtract(appraisalId: string): ExtractResult | undefined {
  return DEMO_EXTRACTS[appraisalId];
}

export function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
